require "minitest/autorun"
require "minitest/rg"
require "sinatra/activerecord"
require_relative "../app/models/age_group.rb"
require_relative "../app/models/location.rb"
require_relative "../app/models/box.rb"
require_relative "../app/models/toy.rb"